import "../styles/globals.css";
import type { AppProps } from "next/app";
import Head from "next/head";

import TopNav from "../components/topnav";
import Footer from "../components/footer";

const DESCRIPTION_TEXT = `MTG Arena Tool is a collection browser, a deck tracker and a statistics manager. Explore which decks you played against and what other players are brewing. MTG Arena Tool is all about improving your Magic Arena experience.`;

const ARTIST = "Thoughtseize by Aleksi Briclot";

function MyApp({ Component, pageProps }: AppProps) {
  return (
    <>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <title>MTG Arena Tool</title>
        <meta name="title" content="MTG Arena Tool" />
        <meta name="description" content={DESCRIPTION_TEXT} />
        <meta name="og:title" content="MTG Arena Tool" />
        <meta name="og:description" content={DESCRIPTION_TEXT} />
        <meta name="og:site:name" content="MTG Arena Tool" />
        <meta name="og:image" content="/favicon.ico" />
        <meta name="og:image:width" content="256" />
        <meta name="og:image:height" content="256" />
        <meta name="og:image:alt" content="MTG Arena Tool Logo" />
        <meta name="twitter:site" content="@mtgatool" />
        <link rel="canonical" href="https://mtgatool.com/" />
      </Head>
      <main>
        <div className="wrapperImage" />
        <TopNav artist={ARTIST} />
        <Component {...pageProps} />
        <Footer />
      </main>
    </>
  );
}

export default MyApp;
